language: node_js
node_js:
- stable
deploy:
  provider: heroku
  api_key:
    secure: r/IEvbmDfnwnt7pdUc79kfROeFqpPJmwjG/q26r5YjHSOjisn8retL7ybgWbFrdem3xu75taFnNdvc7VCNa3Zb5v4zDed0vUpJb/I/+gtHJSx2Po9fFrbJ4P7HAokeX/LkE7dBU9QzyAAtK/dfIuU8fd/twKRQkHcdalcz5NOx4z8S2jTD2SpARx9GMOoztRkvUUuXW9REyZJWIhvcwojXn3ccS4CCeJ6fBDD3PZEoUP+6MU5SI9Cy9bo586uyiksplPbIy8eIM2/9IYTnRuo/IcJ3DUmj7bzrrcrCbn19MbOmdG5argeOrM1XnSgFz5Z33hfs77wFbctOqMwnxWsdd8S0jPY9fhnRF1I1zetfpyewc0OEv1EovqWcsXZcnsv/4oJEUwzssqfXAkgnARUlNnDAm6RrOXrfZbzDZune7/VckPCCiPhKteSbVZRLDTjkPXlavr2SFrs2Lc6OjDDwuG+agNy4lBBgtlyEfWDm0ZsuibYSPu9VqiW4EEig5rDIEFRoLtw7KL5O4y+HA+o24clWUu2p1SKw0cdYzRdVkMkbfA48O52ct1UGVcnDaPT5nDEcQx8/Pw/5mpKLxoctdkW8lMBP/lAXdRco6m6KQsg+IS5BSmO3M8R4+CrgZxG6C2pIs6EKsazozxAmPz25MHvKTHBo5Z0u5WJTZ0Tx8=
  app: heroku-todolist
