language: node_js
node_js:
- stable
deploy:
  provider: heroku
  api_key:
    secure: U7kHDPvkkCP/cKgtoOPgL3P2OO25ZzZG/uYzHHLMCQv/bcqIg7wj5VvtHOt4kfZcfrkx28gsgmlBBV+8in9AlIfwMaWdzNWw7Yie1D+vEaE9abGdqnKA+BV4h+1P2sZuasPsuXIM0dNDgAzST7Is9YCzF5idYNMML+CM5P5zA75itpLzLgX2Jb6Tefi4UNHWI5OMF6Be6cg7TL9AUO0G4vwuyzDDPBJlIADzSivwagSDfCZSoosbKU9YV0t38pyv2xsXWnL7TVGOyphK4U9C4xmkupA9F8YkgnXQucZJzd/UDBpVA8D9s4qBw14ylAgaSblUgVfIET/YwTci8VzyGGFczXTHGyIced1RrttbbaoUoEK1hIGbPlAfyTQe5ED3aaKKGU3BdtWq/OdW3eu7Qzh5Xlghsc0s46862WM4KELmno+8GmhqjmnIY+HWR2lZ78mHdD0WK5iGXL8/MN7QdNt5q6/+UGjhDDHy25n721l+JOsfaIF2ExTiOzAjc4cVMmFFsexuowHlKsbKeNR0ts0OYmS18+oB0u80WSnHTiRsbZ8nLorGLr/+52uzaamQneuzDuAa3oZmv5xQrHq2RXpLlizz2s3piEYTqY42hCTUGzbxWFZdoqFZKPCYkWAlxr7GirbyJS2Qspf6Cm4v+tP12vKFLikeDY/zrLX6tQU=
  app:
    master: heroku-todolist
  on:
    repo: TheoRiviere/devAux
