language: node_js
node_js:
- stable
deploy:
  provider: heroku
  api_key:
    secure: j6f0xTv6Q3VqG6dHF7vJ2UUQxUiwAkevwe5lLwkkKw/WAynQLBw5iXgdHDyKKaaNEY2C3Eu6hNY4bq8or1Vryo9lpieiQxNjMlR5XDWMyVJtvPQlnKDhrq8Lk9BMemzeQ/QvNwFUxyv5+QILtyjI2J6WsNbfxMuwnLgfFr3JmTCl9AalSl210/APGBLT4krwteWyCno0z8ZE0Fa+plH388UR+x0cVJf0fBVJKf1ODBWh+3u+rWUsqC2C3IhkpgbIZDPdouKAWhutWu3Bb0MPtYH+38kMn/1aoZW8OlwJztS87o9LqeST0JMfLHevf8E6Ulcp3CxJ+yp+OmDRPcpwAsLkLXiFSCQ5q0HTbRdhGW/l/BnIeRrDKWtLkpCp067mOToXgyaiRoFtM+Cvlz6IglSfE+ZOTifCiDVmkziIKGdzi7Nl04CAoyL9OfCrvW96Xkkh8lTMhrv7RkQPi83kRBqEU/e5M6x1FCVhFcbsXPRbe4F0yLFo2bB8HxL7xn4tpKeDHDznyOnSuvYycCQ1PbbYRAwEaPu4WqaHwC9jVWGQ20Hd5bqqAwXVLW5sLvM87ALyrrrzUD1SiemngWNH2wtABxy5P+qvCDw6icIPFd0RnkVgqir6ZlRHsjpdyFejOqfocVa8NfSxdpqtXXNt0Aey4b8UqnaUjslaJ8ysPzA=
  app: heroku-todotest
  on:
    repo: TheoRiviere/devAux

addons:
  apt:
    packages:
      - xvfb
install:
  - export DISPLAY=':99.0'
  - Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
  - npm install
